apiVersion: v1
kind: Pod
metadata:
  name: stress-ng-pod
  labels:
    app: stress-ng
spec:
  containers:
  - name: stress-ng
    image: colinianking/stress-ng
    args:
      - "--cpu"
      - "4"
      - "--timeout"
      - "60s"
    resources:
      limits:
        cpu: "8"
        memory: "512Mi"
      requests:
        cpu: "1"
        memory: "256Mi"